### ISSUE TITLE
start_date error on all runs...

### ISSUE THREAD

**Issue by tmsrlabs** [mi01/vaccine-booker-berlin#3]
I have tried this with a few different users...  I can provide more information if necessary.

Traceback (most recent call last):
  File "/Users/todd/Downloads/vaccine-booker-berlin-master/booker.py", line 496, in <module>
    sys.exit(main())
  File "/Users/todd/Downloads/vaccine-booker-berlin-master/booker.py", line 486, in main
    if docto.try_to_book():
  File "/Users/todd/Downloads/vaccine-booker-berlin-master/booker.py", line 230, in try_to_book
    if self.try_to_book_place(profile_id, motive_id, practice_id, agenda_ids):
  File "/Users/todd/Downloads/vaccine-booker-berlin-master/booker.py", line 362, in try_to_book_place
    'start_date': self.page.get_appointment_start_date(),
  File "/Users/todd/Downloads/vaccine-booker-berlin-master/booker.py", line 113, in get_appointment_start_date
    return self.doc['appointment']['start_date']
KeyError: 'start_date'

**Comment by mi01** [comment]
I was able to reproduce this, Doctolib has changed the data format a bit. Should be fixed now.

**Comment by tmsrlabs** [comment]
Now it scheduled both appointments on the second shot appointment date?  strange 
![Unknown](https://user-images.githubusercontent.com/85791586/122012227-3a909900-cdbd-11eb-84e2-bf61379d7be4.jpeg)

**Comment by mi01** [comment]
Sorry for the circumstance, you should cancel that appointment. I overlooked that Doctolib is sending the date of the second slot now, when requesting the appointment edit page. Its working now for me, can you confirm this?

**Comment by tmsrlabs** [comment]
It looks like they've implemented 2fa...  yikes.
